<?php

$term_articles_exact_match = array(
  'Hair' => array(
    '7 Ways to Style Hair for Every Summer Occasion',
    'Homemade Coconut Oil and Honey Hair Mask',
    '10 Quick Ways to Style Long & Short Hair',
    '10 Fancy Ways to Style Long & Short Hair',
    'Beauty Essentials: Hair and Body',
  ),
  'Make-Up' => array(
    '18 Beauty Essentials for The Everygirl',
    'Homemade Honey and Lemon Face Mask',
    '7 Ways to Apply Makeup for Every Summer Occasion',
  ),
  'Life Skills' => array(
    'How to Advance in a Male-Dominated World',
    '5 Easy Ways to Start Negotiating Like A Badass',
    'How to Advance in a Male-Dominated World',
    'Small Business Owners: Tips for De-stressing Tax Season',
    'Living Well: What to Do When You Don’t Yet Know Your Purpose',
    'New Advice Column for Small Business Owners',
    'Living Well: Three Tips to Balance Your Work and Personal Life',
    'Property 101: What You Need to Know When You’re Apartment Hunting',
  ),
  'Relationships' => array(
    'Living Well: How to be in a Healthy and Real Relationship',
    'Living Well: Balancing Friends and a Significant Other',
    'Living Well: How to Handle Massive Change',
    'Living Well: Don’t Let Your Past Relationships Affect Your Present One',
    'Figuring It Out: Would You Date Your Friend?',
    'Living Well: Dealing with Jealousy',
    'What Tinder Taught Me About Dating and Humanity, Ok Just Dating',
    '4 Steps to Building a Smart Marriage',
    'Living Well: Leaving A Negative Situation',
    'Living Well: Don’t Let Your Past Relationships Affect Your Present One',
    'Figuring It Out: Stop Taking Dating Advice',
    'Figuring It Out: No Such Thing as a Blind Date',
  ),
  'Fitness' => array(
    'Lower Body Workout for The Everygirl',
    'Upper Body Workout for The Everygirl',
    'The Everygirl’s Intro to Yoga',
    'The Everygirl’s Indoor Workout for a Small Space',
    'The 30-Minute Workout You Can Do Anywhere',
  ),
  'Physical Health' => array(
    'The Truth About “Health” Foods',
    'Staying Healthy: Avoiding Extreme Measures',
    'A Numbers Game: Why Your Weight Shouldn’t Matter',
    'Staying Healthy on the Go: Take What You Can Get',
    'I’m an Everygirl and… I was diagnosed with vulvar cancer.',
    'Be Bright Pink for National Breast Cancer Awareness Month',
    'Essential Skin Care Tips For The Everygirl',
    'Feel Better, Live Better: 10 Tips for a Healthy Life',
  ),
  'Mental Health' => array(
    'Living Well: Don’t Let Your Past Relationships Affect Your Present One',
    'Living Well: Dealing with Jealousy',
    'What Tinder Taught Me About Dating and Humanity, Ok Just Dating',
    'Living Well: Leaving A Negative Situation',
    'Living Well: Saying Yes to the Unknown',
    'Two Effective Strategies for Managing Stress',
    'Living Well: Ditching Traditional New Year’s Resolutions',
    'Living Well: How to Handle Massive Change',
    'Living Well: Moving Forward After Hearing “No”',
    'Living Well: Use Your Intuition to Make Big Decisions',
    'Living Well: What to Do When You Don’t Yet Know Your Purpose',
    'Living Well: Three Tips to Balance Your Work and Personal Life',
    'Stressed? Top 5 Foods to Chill You Out',
    'Living Well: Learning to Say No',
    'Figuring It Out: The F Word',
    'Figuring It Out: Age Ain’t Nothing But a Number…Right?',
  ),
  'Wedding' => array(
    'Ways to Save on Your Wedding Day',
    'The Everygirl’s Backyard Wedding',
    'The Everygirl’s Wedding Registry Guide',
    'Styling a Wedding Table by Cassandra LaValle',
    'How to Style a Wedding Table by Camille Styles',
    'How to Style a Wedding Table by Anne Book',
    'Wedding Week: Backyard Bridal Shower',
    'Wedding Week: Budget-friendly Bridal Fashion',
    'Wedding Week: Budget-friendly Bridesmaid Fashion',
  ),
  'DIY' => array(
    'A Simple Halloween DIY to Spook Up Your Home',
    'The DIY Files: Glitter Mousepad and Pencil Cup',
    'The DIY Files: Personalized Polka Dot Coasters',
    'Furniture Rehab with Centsational Girl',
    'The DIY Files: Knotted Rope Necklace with Grace Atwood',
  ),
  'Decor' => array(
    '10 Money-Saving Decorating Tips We’ve Learned from Everygirl Home Tours',
    'Win a $5000 Dream Room & $1000 Styling Giveaway from The Everygirl + Fizz56!',
    'How to Style Wire Shelves for a Living Space and Kitchen',
    'Styling a Tabletop Made Easy with Cassandra Lavalle and Furbish',
    'How to Style a Simple Spring Brunch',
    'The Everygirl’s Favorite Sources for Pillows',
    'How to Style the West Elm Parsons Desk',
    'The Everygirl’s “How to Style” Sale on Joss and Main',
    'Holiday Week: 12 Easy & Affordable Tips to Bring the Holidays into Your Home',
    'How to Style Flowers',
    'The Everygirl’s Ten Favorite Ikea Finds',
    'How to Style a Bed',
    'How to Style a Nightstand',
    'How to Style Kitchen Countertops',
    'How to Style a Coffee Table',
    'Place Settings: Get the Look',
    'How to Set and Style a Place Setting',
    'How to Style an Entryway',
  ),
  'Entertaining' => array(
    'Entertaining for Beginners: Host a Game Night',
    'How to Throw an End of Summer Soiree',
    'The No Fuss Dinner Party for Everygirls',
    'The Everygirl’s Valentine’s Day Soiree',
  ),
  'Fashion Styling' => array(
    'Bringing Color Into Budget-Friendly Fall Fashion',
    'Leather: Why Everyone Can Wear It',
    'Three Looks: Carly Haslee of A Simple Affair',
    'Three Looks: Courtney Kerr of What Courtney Wore',
    'Three Looks: Melanie Pace Styles Spring Jackets',
    'Three Trends Two Ways with Glitterary',
    'Three Looks: Mara Ferreira of M Loves M',
    'Three Looks: Lauren of Stylized Existence',
    'Three Looks: Krystal Knight of The Feisty House',
    'Three Looks: Anna Jane Wisniewski of See Jane',
    'Three Looks: Nicole Levine of Frankie Hearts Fashion',
    'Three Looks: Elizabeth Schneider of Sequins and Stripes',
    'Three Looks: Audrey Huber of A Lovely Escape',
    'Holiday Week: 6 Looks to Get You Through Every Festive Fete',
    'The Everygirls Go to New York Fashion Week',
    'Brights Are the New Neutral: Starring Coach & Chicago’s Finest',
    'Get Interview Ready with IFB',
    'Transcend the Office Dress Code with IFB',
    'Wedding Week: Budget-friendly Bridal Fashion',
    'Wedding Week: Budget-friendly Bridesmaid Fashion',
    'Styling from Winter to Spring',
    'The Everygirls Go to New York Fashion Week',
  ),
  'Shopping' => array(
    'Fashion Essentials: Tailored Blazer',
    'Leopard Print: Fall’s Go-To Neutral',
    'Fashion Essentials and Giveaway: Ballet Flats',
    'Fashion Essentials and Giveaway: Little Black Dress',
    'Fashion Essentials: Summer Scarf',
    'Fashion Essentials and Giveaway: White Jeans',
    'Fashion Essentials and Giveaway: Summer Heels',
    'The Everygirl’s Fashion Essentials: The Striped Tee',
    'Affordable Fashion for Every Person at Any Wedding',
    'Three Summer Looks with Stephanie Sterjovski',
    'The Everygirl Shops: Spring Jackets',
    'Holiday Week: The Everygirl’s Gift Guide',
    'What to Pack: Essentials for Your Carry-on, Work Bag, and Gym Bag',
    'Fashion Essentials: Fall Footwear',
    'Fashion Essentials for The Everygirl: Part 3',
    'Fashion Essentials for The Everygirl: Part 2',
    'Fashion Essentials for The Everygirl',
    'Everygirls of Summer: Staff Picks Under $100',
    'Everygirls Picked: Spring Flats for Under $100',
    'The Mother’s Day Gift Guide',
    'Holiday Week: The Everygirl’s Gift Guide',
  ),
  'Travel Journal' => array(
    'Summer Staycation + Starwood Hotels Giveaway!',
  ),
  'Hotels' => array(
    'TRAVEL GUIDE: The Inn at St. Botolph in Boston',
    'Summer Staycation + Starwood Hotels Giveaway!',
  ),
  'Restaurants' => array(
    'TRAVEL GUIDE: South End Buttery',
    'TRAVEL GUIDE: Stella Restaurant and Bar',
  ),
  'Living Well' => array(
    'Lessons in Motherhood',
  ),
  'Opinion' => array(
    '9 Reasons to Boycott Slutty Costumes This Halloween',
  )
);

?>